services:
  - type: web
    name: n8n-whatsapp-bot
    env: docker
    plan: free
    autoDeploy: true
    region: singapore
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: https
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: WEBHOOK_URL
        sync: false
